on:
  pull_request:
    branches:
    - main
name: ci
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: ^1.16
    - name: Checkout
      uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Install tools
      run: sudo apt-get update && sudo apt-get install -y make gcc
    - name: Test
      run: make test
